# -*- coding: utf-8 -*-
""" 
Ensemble of functions to characterize audio signals using multiple acoustic 
features and ecoacoustic indices.
"""

from .shape import (filter_multires,
                          filter_bank_2d_nodc,
                          opt_shape_presets,
                          shape_features,
                          shape_features_raw,
                          plot_shape,
                          centroid_features,
                          overlay_centroid,
                          all_shape_features)

from .music import (moments,
                    zero_crossing_rate)

from .alpha_indices import (audio_moments,
                            audio_median,
                            audio_entropy,
                            acousticRichnessIndex,
                            audio_activity,
                            audio_events,
                            acousticComplexityIndex,
                            frequency_entropy,
                            numberOfPeaks,
                            spectral_entropy,
                            spectral_moments,
                            spectral_activity,
                            spectral_events,
                            spectral_cover,
                            soundscapeIndex,
                            bioacousticsIndex,
                            acousticDiversityIndex,
                            acousticEvenessIndex,
                            roughness,
                            audio_LEQ,
                            spectral_LEQ,
                            surfaceRoughness,
                            tfsd,
                            more_entropy,
                            acousticGradientIndex,
                            frequency_raoQ,
                            regionOfInterestIndex,
                            all_audio_alpha_indices,
                            all_spectral_alpha_indices)

__all__ = [
           # shape
           'filter_multires', 
           'filter_bank_2d_nodc',
           'opt_shape_presets',
           'shape_features',
           'shape_features_raw',
           'plot_shape',
           'centroid_features',
           'overlay_centroid',
           'all_shape_features',
           # music
           'moments',
           'zero_crossing_rate',
           # alpha_indices
           'audio_moments',
           'audio_median',
           'audio_entropy',
           'acousticRichnessIndex',
           "audio_activity",
           "audio_events",
           "acousticComplexityIndex",
           "frequency_entropy",
           "numberOfPeaks",
           "spectral_entropy",
           "spectral_moments",
           "spectral_activity",
           "spectral_events",
           'spectral_cover',
           "soundscapeIndex",
           'bioacousticsIndex',
           "acousticDiversityIndex",
           "acousticEvenessIndex",
           "roughness",
           'audio_LEQ',
           'spectral_LEQ',
           "surfaceRoughness",
           "tfsd",
           "more_entropy",
           "acousticGradientIndex",
           "frequency_raoQ",
           "regionOfInterestIndex",
           'all_audio_alpha_indices',
           'all_spectral_alpha_indices']