# -*- coding: utf-8 -*-
""" 
Ensemble of functions to compute acoustic features and characterize audio signals.
"""

from .features_2d import (filter_multires,
                          filter_bank_2d_nodc,
                          opt_shape_presets,
                          shape_features,
                          shape_features_raw,
                          plot_shape,
                          centroid_features,
                          overlay_centroid,
                          compute_all_features)

from .features_1d import (psd, 
                          rms,
                          skewness,
                          kurtosis,
                          zero_crossing_rate)

from .alpha_indices import (audio_moments,
                            audio_median,
                            audio_entropy,
                            acousticRichnessIndex,
                            audio_activity,
                            audio_events,
                            acousticComplexityIndex,
                            frequency_entropy,
                            numberOfPeaks,
                            spectral_entropy,
                            spectral_moments,
                            spectral_activity,
                            spectral_events,
                            spectral_cover,
                            soundscapeIndex,
                            bioacousticsIndex,
                            acousticDiversityIndex,
                            acousticEvenessIndex,
                            roughness,
                            audio_LEQ,
                            spectral_LEQ,
                            surfaceRoughness,
                            tfsd,
                            more_entropy,
                            acousticGradientIndex,
                            frequency_raoQ,
                            regionOfInterestIndex,
                            audio_indices,
                            spectral_indices)

__all__ = [
           # features_2d
           'filter_multires', 
           'filter_bank_2d_nodc',
           'opt_shape_presets',
           'shape_features',
           'shape_features_raw',
           'plot_shape',
           'centroid_features',
           'overlay_centroid',
           'compute_all_features',
           # features_1d
           'psd',
           'rms',
           'skewness',
           'kurtosis',
           'zero_crossing_rate',
           # alpha_indices
           'audio_moments',
           'audio_median',
           'audio_entropy',
           'acousticRichnessIndex',
           "audio_activity",
           "audio_events",
           "acousticComplexityIndex",
           "frequency_entropy",
           "numberOfPeaks",
           "spectral_entropy",
           "spectral_moments",
           "spectral_activity",
           "spectral_events",
           'spectral_cover',
           "soundscapeIndex",
           'bioacousticsIndex',
           "acousticDiversityIndex",
           "acousticEvenessIndex",
           "roughness",
           'audio_LEQ',
           'spectral_LEQ',
           "surfaceRoughness",
           "tfsd",
           "more_entropy",
           "acousticGradientIndex",
           "frequency_raoQ",
           "regionOfInterestIndex",
           'audio_indices',
           'spectral_indices']